version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leavebot
      MYSQL_USER: slack
      MYSQL_PASSWORD: password
    ports: 
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${OAUTH_TOKEN}
      SIGNING_SECRET: ${SIGNING_SECRET}
      APP_TOKEN: ${APP_TOKEN}
      DB_HOST: db
      DB_USER: slack
      DB_PASSWORD: password
      DB_NAME: leavebot
      DB_PORT: 3306
    ports:
      - "3000:3000"

volumes:
  db_data:
